### ISSUE TITLE
Ezno public? Open to contributions?

### ISSUE THREAD

**Issue by austintheriot** [kaleidawave/kaleidawave.github.io#1]
Hi Ben! I found your blog post on Ezno today from the JavaScript weekly news letter. Really amazing stuff! I didn't immediately find Ezno in your list of repos though. Is it currently private? I would be really interested in contributing to the project. I have experience with Rust, advanced TypeScript, and I'm currently learning more about type theory / dependent types. 

I love your idea of automatic generic typing for Ezno and the ability to do more advanced dependent-type-level manipulations like addition with types. 

Thanks!

**Comment by kaleidawave** [comment]
Ah that is cool it got featured there! No not public yet, as mentioned in the last line in the post. Need a few more architectural stuff in place and some tidying up. Then some of the internals need documenting for contributions to be easier. That is great that you have some experience and are learning more! Will announce status updates here: https://twitter.com/kaleidawave
