### ISSUE TITLE
Expose RSS feed

### ISSUE THREAD

**Issue by gBasil** [kaleidawave/kaleidawave.github.io#3]
From what I can see, the website doesn't say that an RSS feed is available anywhere. I had to go to this repository and search for "RSS" in order to find the feed URL. It would be nice to have it available somewhere, perhaps through a `<link>` in the `<head>`.

**Comment by lishaduck** [comment]
It is exposed on the about page now, but a `<link rel="alternate" type="application/rss+xml" href="/feed.xml" />` would still help.
